dirs:
    train:
        data: /data/sxu/easton/data/TIMIT/train_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/tmp/train_39
    dev:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
        tfdata: /data/sxu/easton/data/TIMIT/tfdata/tmp/dev_39
    test:
        data: /data/sxu/easton/data/TIMIT/test_phone39.csv
    type: csv
    vocab: /data/sxu/easton/data/TIMIT/phone39.list
    ngram: /data/sxu/easton/projects/EODM/all.ngram
    # restore: /data/sxu/easton/projects/EODM/models/FC_phone_level/init_checkpoint
    # restore: /data/sxu/easton/projects/EODM/models/timit_es2/checkpoint

data:
    featType: fbank
    dim_raw_input: 13
    num_context: 5
    downsample: 1
    add_delta: True
    unit: word
    full_align: True
    ngram: 5
    top_k: 1300
    k: 1300

model:
    structure: fc
    training_type: teacher-forcing
    loss_type: CE
    num_hidden: 128
    num_layers: 1

opti:
    lr: 0.005
    population: 100
    sigma: 0.05

dev_step: 5
decode_step: 100
save_step: 50
fs_step: 500000

gpus: '0,1,2,3'
# gpus: '1,2,3'
batch_size: 2000
batch_multi: 1
num_batch_tokens: 780000
bucket_boundaries: 238,300,372,437,800
num_epochs: 100000
num_steps: 500000
num_threads: 2

lambda_fs: 0.000001

grad_clip_global_norm: 0.0
